FROM rockylinux/rockylinux:8.10
LABEL maintainer="TabPaD <tabpad@hotmail.com>"
RUN  dnf -y groupinstall "Development Tools" \
  && dnf install -y epel-release rpmdevtools curl tar rsync --allowerasing \
  && dnf clean all \
  && rm -rf /var/cache/yum
